import apiClient from './apiConfig';

// Dashboard data interface
export interface DashboardData {
    user: {
        id: string;
        userName: string;
        email: string;
        firstName: string;
        lastName: string;
        phoneNumber: string;
        lastLogin: string;
        roleId: string;
        roleName: string;
        isEmailVerified: boolean;
        createdTime: string;
        isActivated: boolean;
    };
    donorProfile: {
        id: string;
        dateOfBirth: string;
        gender: boolean;
        lastDonationDate: string;
        healthStatus: string;
        lastHealthCheckDate: string;
        totalDonations: number;
        address: string;
        latitude: string;
        longitude: string;
        userId: string;
        userName: string;
        bloodGroupId: string;
        bloodGroupName: string;
        createdTime: string;
        lastUpdatedTime: string;
        nextAvailableDonationDate: string;
        isAvailableForEmergency: boolean;
        preferredDonationTime: string;
        distanceKm: number;
        isEligible: boolean;
        firstName: string;
        lastName: string;
        phoneNumber: string;
        email: string;
    };
    isEligibleToDonate: boolean;
    ineligibilityReason: string;
    nextEligibleDonationDate: string;
    recentDonations: Array<{
        id: string;
        donorId: string;
        donorName: string;
        donorEmail: string;
        donorPhone: string;
        bloodGroupId: string;
        bloodGroupName: string;
        componentTypeId: string;
        componentTypeName: string;
        locationId: string;
        locationName: string;
        locationAddress: string;
        staffId: string;
        staffName: string;
        requestType: string;
        requestId: string;
        appointmentDate: string;
        appointmentLocation: string;
        appointmentConfirmed: boolean;
        status: string;
        statusDescription: string;
        notes: string;
        bloodPressure: string;
        temperature: number;
        hemoglobinLevel: number;
        weight: number;
        height: number;
        medicalNotes: string;
        rejectionReason: string;
        donationDate: string;
        donationStartTime: string;
        quantityDonated: number;
        quantityUnits: number;
        isUsable: boolean;
        complicationType: string;
        complicationDetails: string;
        actionTaken: string;
        createdTime: string;
        lastUpdatedTime: string;
        checkInTime: string;
        completedTime: string;
        deletedTime: string;
        isActive: boolean;
    }>;
    totalDonationsCount: number;
    totalDonationVolume: number;
    estimatedLivesSaved: number;
    upcomingAppointments: Array<{
        id: string;
        donorId: string;
        donorName: string;
        donorEmail: string;
        donorPhone: string;
        totalDonations: number;
        lastDonationDate: string;
        nextEligibleDonationDate: string;
        preferredDate: string;
        preferredTimeSlot: string;
        locationId: string;
        locationName: string;
        locationAddress: string;
        bloodGroupId: string;
        bloodGroupName: string;
        componentTypeId: string;
        componentTypeName: string;
        requestType: string;
        initiatedByUserId: string;
        initiatedByUserName: string;
        status: string;
        notes: string;
        rejectionReason: string;
        reviewedByUserId: string;
        reviewedByUserName: string;
        reviewedAt: string;
        confirmedDate: string;
        confirmedTimeSlot: string;
        confirmedLocationId: string;
        confirmedLocationName: string;
        donorAccepted: boolean;
        donorResponseAt: string;
        donorResponseNotes: string;
        workflowId: string;
        isUrgent: boolean;
        priority: number;
        createdTime: string;
        lastUpdatedTime: string;
        expiresAt: string;
        checkInTime: string;
        completedTime: string;
        cancelledTime: string;
    }>;
    myBloodRequests: Array<{
        id: string;
        quantityUnits: number;
        requestDate: string;
        status: string;
        isEmergency: boolean;
        neededByDate: string;
        requestedBy: string;
        requesterName: string;
        patientName: string;
        urgencyLevel: string;
        contactInfo: string;
        hospitalName: string;
        bloodGroupId: string;
        bloodGroupName: string;
        componentTypeId: string;
        componentTypeName: string;
        locationId: string;
        locationName: string;
        address: string;
        latitude: string;
        longitude: string;
        distanceKm: number;
        medicalNotes: string;
        isActive: boolean;
        fulfilledDate: string;
        fulfilledByStaffId: string;
        fulfilledByStaffName: string;
        isPickedUp: boolean;
        pickupDate: string;
        pickupNotes: string;
        createdTime: string;
        lastUpdatedTime: string;
    }>;
    recentNotifications: Array<{
        id: string;
        type: string;
        message: string;
        isRead: boolean;
        userId: string;
        userName: string;
        createdTime: string;
        lastUpdatedTime: string;
    }>;
    nearbyEmergencyRequests: Array<{
        id: string;
        patientName: string;
        urgencyLevel: string;
        contactInfo: string;
        hospitalName: string;
        quantityUnits: number;
        bloodGroupId: string;
        bloodGroupName: string;
        componentTypeId: string;
        componentTypeName: string;
        address: string;
        latitude: string;
        longitude: string;
        medicalNotes: string;
        status: string;
        requestDate: string;
        createdTime: string;
    }>;
    achievementBadges: string[];
    nearbyDonationCenters: Array<{
        id: string;
        name: string;
        address: string;
        latitude: string;
        longitude: string;
        isActive: boolean;
        description: string;
        contactPhone: string;
        contactEmail: string;
        createdTime: string;
        lastUpdatedTime: string;
        capacities: Array<{
            id: string;
            locationId: string;
            locationName: string;
            timeSlot: string;
            totalCapacity: number;
            dayOfWeek: number;
            effectiveDate: string;
            expiryDate: string;
            isActive: boolean;
            notes: string;
            createdTime: string;
            lastUpdatedTime: string;
        }>;
        staffAssignments: Array<{
            id: string;
            locationId: string;
            locationName: string;
            userId: string;
            userName: string;
            userEmail: string;
            role: string;
            canManageCapacity: boolean;
            canApproveAppointments: boolean;
            canViewReports: boolean;
            assignedDate: string;
            unassignedDate: string;
            isActive: boolean;
            notes: string;
            createdTime: string;
            lastUpdatedTime: string;
        }>;
    }>;
}

// Staff Dashboard data interface
export interface StaffDashboardData {
    activeBloodRequests: Array<{
        id: string;
        quantityUnits: number;
        requestDate: string;
        status: string;
        isEmergency: boolean;
        neededByDate: string;
        requestedBy: string;
        requesterName: string;
        patientName: string;
        urgencyLevel: string;
        contactInfo: string;
        hospitalName: string;
        bloodGroupId: string;
        bloodGroupName: string;
        componentTypeId: string;
        componentTypeName: string;
        locationId: string;
        locationName: string;
        address: string;
        latitude: string;
        longitude: string;
        distanceKm: number;
        medicalNotes: string;
        isActive: boolean;
        fulfilledDate: string;
        fulfilledByStaffId: string;
        fulfilledByStaffName: string;
        isPickedUp: boolean;
        pickupDate: string;
        pickupNotes: string;
        createdTime: string;
        lastUpdatedTime: string;
    }>;
    emergencyRequests: Array<{
        id: string;
        patientName: string;
        urgencyLevel: string;
        contactInfo: string;
        hospitalName: string;
        quantityUnits: number;
        bloodGroupId: string;
        bloodGroupName: string;
        componentTypeId: string;
        componentTypeName: string;
        address: string;
        latitude: string;
        longitude: string;
        medicalNotes: string;
        status: string;
        requestDate: string;
        createdTime: string;
    }>;
    requestStatusCounts: Record<string, number>;
    inventorySummary: Array<{
        bloodGroupId: string;
        bloodGroupName: string;
        componentTypeId: string;
        componentTypeName: string;
        availableQuantity: number;
        minimumRecommended: number;
        optimalQuantity: number;
        status: string;
        availabilityPercentage: number;
    }>;
    recentAppointments: Array<{
        id: string;
        donorId: string;
        donorName: string;
        donorEmail: string;
        donorPhone: string;
        totalDonations: number;
        lastDonationDate: string;
        nextEligibleDonationDate: string;
        preferredDate: string;
        preferredTimeSlot: string;
        locationId: string;
        locationName: string;
        locationAddress: string;
        bloodGroupId: string;
        bloodGroupName: string;
        componentTypeId: string;
        componentTypeName: string;
        requestType: string;
        initiatedByUserId: string;
        initiatedByUserName: string;
        status: string;
        notes: string;
        rejectionReason: string;
        reviewedByUserId: string;
        reviewedByUserName: string;
        reviewedAt: string;
        confirmedDate: string;
        confirmedTimeSlot: string;
        confirmedLocationId: string;
        confirmedLocationName: string;
        donorAccepted: boolean;
        donorResponseAt: string;
        donorResponseNotes: string;
        workflowId: string;
        isUrgent: boolean;
        priority: number;
        createdTime: string;
        lastUpdatedTime: string;
        expiresAt: string;
        checkInTime: string;
        completedTime: string;
        cancelledTime: string;
    }>;
    upcomingAppointments: Array<{
        id: string;
        donorId: string;
        donorName: string;
        donorEmail: string;
        donorPhone: string;
        totalDonations: number;
        lastDonationDate: string;
        nextEligibleDonationDate: string;
        preferredDate: string;
        preferredTimeSlot: string;
        locationId: string;
        locationName: string;
        locationAddress: string;
        bloodGroupId: string;
        bloodGroupName: string;
        componentTypeId: string;
        componentTypeName: string;
        requestType: string;
        initiatedByUserId: string;
        initiatedByUserName: string;
        status: string;
        notes: string;
        rejectionReason: string;
        reviewedByUserId: string;
        reviewedByUserName: string;
        reviewedAt: string;
        confirmedDate: string;
        confirmedTimeSlot: string;
        confirmedLocationId: string;
        confirmedLocationName: string;
        donorAccepted: boolean;
        donorResponseAt: string;
        donorResponseNotes: string;
        workflowId: string;
        isUrgent: boolean;
        priority: number;
        createdTime: string;
        lastUpdatedTime: string;
        expiresAt: string;
        checkInTime: string;
        completedTime: string;
        cancelledTime: string;
    }>;
    recentDonations: Array<{
        id: string;
        donorId: string;
        donorName: string;
        donorEmail: string;
        donorPhone: string;
        bloodGroupId: string;
        bloodGroupName: string;
        componentTypeId: string;
        componentTypeName: string;
        locationId: string;
        locationName: string;
        locationAddress: string;
        staffId: string;
        staffName: string;
        requestType: string;
        requestId: string;
        appointmentDate: string;
        appointmentLocation: string;
        appointmentConfirmed: boolean;
        status: string;
        statusDescription: string;
        notes: string;
        bloodPressure: string;
        temperature: number;
        hemoglobinLevel: number;
        weight: number;
        height: number;
        medicalNotes: string;
        rejectionReason: string;
        donationDate: string;
        donationStartTime: string;
        quantityDonated: number;
        quantityUnits: number;
        isUsable: boolean;
        complicationType: string;
        complicationDetails: string;
        actionTaken: string;
        createdTime: string;
        lastUpdatedTime: string;
        checkInTime: string;
        completedTime: string;
        deletedTime: string;
        isActive: boolean;
    }>;
    expiringInventory: Array<{
        id: number;
        quantityUnits: number;
        expirationDate: string;
        status: string;
        inventorySource: string;
        bloodGroupId: string;
        bloodGroupName: string;
        componentTypeId: string;
        componentTypeName: string;
        donationEventId: string;
        donorName: string;
        donationEvent: {
            id: string;
            donorId: string;
            donorName: string;
            donorPhone: string;
            donationDate: string;
            quantityDonated: number;
            quantityUnits: number;
            isUsable: boolean;
            locationId: string;
            locationName: string;
            createdTime: string;
            completedTime: string;
        };
    }>;
    todayActivity: {
        donationsToday: number;
        newRequestsToday: number;
        fulfilledRequestsToday: number;
        newDonorsToday: number;
        totalVolumeCollectedToday: number;
        emergencyRequestsToday: number;
    };
    availableEmergencyDonors: Array<{
        id: string;
        dateOfBirth: string;
        gender: boolean;
        lastDonationDate: string;
        healthStatus: string;
        lastHealthCheckDate: string;
        totalDonations: number;
        address: string;
        latitude: string;
        longitude: string;
        userId: string;
        userName: string;
        bloodGroupId: string;
        bloodGroupName: string;
        createdTime: string;
        lastUpdatedTime: string;
        nextAvailableDonationDate: string;
        isAvailableForEmergency: boolean;
        preferredDonationTime: string;
        distanceKm: number;
        isEligible: boolean;
        firstName: string;
        lastName: string;
        phoneNumber: string;
        email: string;
    }>;
    trends: {
        donationTrend: Record<string, number>;
        requestTrend: Record<string, number>;
        emergencyTrend: Record<string, number>;
        inventoryTrend: Record<string, Record<string, number>>;
    };
}

export interface ApiResponse<T> {
    success: boolean;
    message: string;
    statusCode: number;
    errors: string[];
    data: T;
    count: number;
}

/**
 * Get member dashboard data
 * @returns Promise with dashboard data
 */
export const getMemberDashboard = async (): Promise<ApiResponse<DashboardData>> => {
    const response = await apiClient.get<ApiResponse<DashboardData>>('/Dashboard/member');
    return response.data;
};

/**
 * Get admin dashboard data
 * @returns Promise with dashboard data
 */
export const getAdminDashboard = async (): Promise<ApiResponse<any>> => {
    const response = await apiClient.get<ApiResponse<any>>('/Dashboard/admin');
    return response.data;
};

/**
 * Get staff dashboard data
 * @returns Promise with dashboard data
 */
export const getStaffDashboard = async (): Promise<ApiResponse<StaffDashboardData>> => {
    const response = await apiClient.get<ApiResponse<StaffDashboardData>>('/Dashboard/staff');
    return response.data;
}; 